import { createFileRoute } from "@tanstack/react-router";
import { Check, Lock, LogOut, Power, RefreshCw, X } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { Button } from "@/components/ui/button";
import { adminLogin, adminLogout, getAdminPayments, getAdminUsers, setPaymentStatus, setUserActive, type PaymentRequest, type User } from "@/lib/auth";

export const Route = createFileRoute("/admin")({ component: AdminPage });
function AdminPage(){
 const [logged,setLogged]=useState(false);const [username,setUsername]=useState("");const [password,setPassword]=useState("");const [users,setUsers]=useState<User[]>([]);const [payments,setPayments]=useState<PaymentRequest[]>([]);const [error,setError]=useState("");const [loading,setLoading]=useState(false);
 const load=async()=>{try{const [u,p]=await Promise.all([getAdminUsers(),getAdminPayments()]);setUsers(u.users);setPayments(p.payments);setLogged(true);setError("");}catch(e){setLogged(false);setError(e instanceof Error?e.message:"Huna ruhusa.");}};
 useEffect(()=>{void load();},[]);
 const login=async(e:FormEvent)=>{e.preventDefault();setLoading(true);try{await adminLogin(username,password);await load();}catch(e){setError(e instanceof Error?e.message:"Login ya admin imeshindikana.");}finally{setLoading(false);}};
 const changeUser=async(id:string,active:boolean)=>{await setUserActive(id,active);await load();};
 const changePayment=async(id:string,status:"approved"|"rejected")=>{await setPaymentStatus(id,status);await load();};
 if(!logged)return <main className="min-h-screen bg-background px-4 py-10 text-foreground"><div className="mx-auto max-w-md rounded-xl bg-card p-6 text-card-foreground shadow-xl"><div className="text-center"><div className="mx-auto grid size-14 place-items-center rounded-full bg-accent"><Lock/></div><h1 className="mt-4 font-display text-3xl font-extrabold">Admin Login</h1><p className="mt-2 text-sm text-card-muted">Ingiza credentials za admin.</p></div><form onSubmit={login} className="mt-6 space-y-4"><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Admin username" className="w-full rounded-lg border border-input bg-background px-4 py-3" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" className="w-full rounded-lg border border-input bg-background px-4 py-3" required/>{error&&<p className="text-sm font-bold text-destructive">{error}</p>}<Button type="submit" className="w-full" disabled={loading}>{loading?"Inaingia...":"INGIA ADMIN"}</Button></form></div></main>;
 return <main className="min-h-screen bg-background px-4 py-6 text-foreground"><div className="mx-auto max-w-5xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm font-semibold text-page-muted">Tvideo Control Panel</p><h1 className="font-display text-3xl font-extrabold">Admin Dashboard</h1></div><div className="flex gap-2"><Button variant="card" onClick={()=>void load()}><RefreshCw className="size-4"/> Refresh</Button><Button variant="cancel" onClick={async()=>{await adminLogout();setLogged(false);}}><LogOut className="size-4"/> Logout</Button></div></div>
 <section className="mt-6 rounded-xl bg-card p-5 text-card-foreground shadow-lg"><h2 className="font-display text-xl font-extrabold">Payment Requests</h2><div className="mt-4 space-y-3">{payments.length===0?<p className="text-sm text-card-muted">Hakuna payment request.</p>:payments.map(p=><div key={p.id} className="rounded-lg border border-card-border p-4"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{p.fullName} (@{p.username})</p><p className="text-sm text-card-muted">Ameleta simu: {p.phone} • {p.amount.toLocaleString()} TZS</p><p className="text-xs text-card-muted">{new Date(p.createdAt).toLocaleString()}</p></div><span className="rounded-md bg-receipt-chip px-2 py-1 text-xs font-bold">{p.status}</span></div>{p.status==="pending"&&<div className="mt-3 flex gap-2"><Button variant="primary" size="compact" onClick={()=>void changePayment(p.id,"approved")}><Check className="size-4"/> Approve & Activate</Button><Button variant="cancel" size="compact" onClick={()=>void changePayment(p.id,"rejected")}><X className="size-4"/> Reject</Button></div>}</div>)}</div></section>
 <section className="mt-6 rounded-xl bg-card p-5 text-card-foreground shadow-lg"><h2 className="font-display text-xl font-extrabold">Users</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead><tr className="border-b border-card-border"><th className="p-3">User</th><th className="p-3">Simu</th><th className="p-3">Status</th><th className="p-3">Action</th></tr></thead><tbody>{users.map(u=><tr key={u.id} className="border-b border-card-border"><td className="p-3"><strong>{u.fullName}</strong><br/><span className="text-card-muted">@{u.username}</span></td><td className="p-3">{u.phone}</td><td className="p-3">{u.active?<span className="font-bold text-success">Active</span>:<span className="font-bold text-destructive">Inactive</span>}</td><td className="p-3"><Button size="compact" variant={u.active?"cancel":"primary"} onClick={()=>void changeUser(u.id,!u.active)}><Power className="size-4"/>{u.active?"Deactivate":"Activate"}</Button></td></tr>)}</tbody></table></div></section>
 </div></main>;
}
