import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, CheckCircle2, CreditCard } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { getMe, submitPaymentRequest } from "@/lib/auth";
import { ACTIVATION_FEE, PaymentInstructions } from "@/components/PaymentInstructions";

export const Route = createFileRoute("/payment")({ component: PaymentPage });
function PaymentPage(){
 const navigate=useNavigate(); const [user,setUser]=useState<Awaited<ReturnType<typeof getMe>>["user"]>(null); const [phone,setPhone]=useState(""); const [step,setStep]=useState(0); const [message,setMessage]=useState(""); const [loading,setLoading]=useState(false);
 useEffect(()=>{getMe().then(r=>setUser(r.user)).catch(()=>setUser(null));},[]);
 const confirm=async()=>{if(step===0){setStep(1);setMessage("FANYA MALIPO KISHA JARIBU TENA");return;} if(!phone.trim())return setMessage("Weka namba ya simu uliyotumia kulipia.");setLoading(true);try{await submitPaymentRequest(phone.trim());setStep(2);setMessage("Ombi lako limetumwa. Admin atahakikisha malipo kisha ata-activate account yako.");}catch(e){setMessage(e instanceof Error?e.message:"Imeshindikana kutuma taarifa.");}finally{setLoading(false);}};
 return <main className="min-h-screen bg-background px-4 py-8 text-foreground"><div className="mx-auto max-w-2xl"><Link to="/" className="inline-flex items-center gap-2 text-sm font-bold text-page-muted"><ArrowLeft className="size-4"/> Rudi</Link><div className="mt-5"><div className="rounded-xl bg-card p-6 text-card-foreground shadow-xl"><div className="flex items-center gap-3"><div className="grid size-12 place-items-center rounded-full bg-accent"><CreditCard/></div><div><h1 className="font-display text-2xl font-extrabold">Activate Account</h1><p className="text-sm font-semibold text-card-muted">Lipa {ACTIVATION_FEE.toLocaleString()} TZS ili account yako iweze ku-activate.</p></div></div>{user&&<div className="mt-4 rounded-lg bg-receipt-bg p-3 text-sm font-semibold">Account: <strong>{user.username}</strong>{user.active?<span className="ml-2 text-success">✓ Active</span>:<span className="ml-2 text-destructive">• Haija-activate</span>}</div>}<div className="mt-5"><PaymentInstructions/></div>{step<2&&<div className="mt-5 rounded-lg border border-accent/30 bg-accent/10 p-4">{step===1&&<label className="block text-sm font-bold">Namba ya simu uliyolipia<input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="07XXXXXXXX" className="mt-1 w-full rounded-lg border border-input bg-background px-4 py-3"/></label>}<Button type="button" variant="accent" size="lg" className="mt-3 w-full font-display font-extrabold" onClick={confirm} disabled={loading}>{step===0?"NIMELIPIA":loading?"Inatuma...":"NIMELIPIA"}</Button>{message&&<p className="mt-3 text-center text-sm font-extrabold text-destructive">{message}</p>}</div>}{step===2&&<div className="mt-5 rounded-lg bg-profit p-5 text-profit-foreground"><div className="flex gap-3"><CheckCircle2 className="size-8 shrink-0"/><div><p className="font-display text-lg font-extrabold">Taarifa zimetumwa</p><p className="mt-1 text-sm font-semibold text-profit-muted">{message}</p></div></div></div>}{!user&&<p className="mt-5 text-center text-sm font-semibold text-card-muted">Anza kwa <Link to="/register" className="font-extrabold text-primary">kujifungua account</Link> au <Link to="/login" className="font-extrabold text-primary">Log in</Link>.</p>}{user?.active&&<Button variant="primary" className="mt-5 w-full" onClick={()=>navigate({to:"/"})}>Endelea Dashboard</Button>}</div></div></div></main>;
}
